<?php
include_once("../common.php");

header("Content-type: text/plain");
?>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tw: <http://tw.rpi.edu/schema/>
PREFIX twi: <http://tw.rpi.edu/instances/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bcodmo: <http://escience.rpi.edu/ontology/BCO-DMO/bcodmo/2/0/>

DESCRIBE ?deployment ?platform
WHERE {
  ?deployment rdf:type bcodmo:Deployment .
  OPTIONAL {
    ?deployment bcodmo:ofPlatform ?platform .
  }
}
