<?php

include_once("common.php");

if(isset($_GET["uri"])) {
  $instance = "<" . sanitize($_GET["uri"],false) . ">";
}
else if(isset($_GET["i"])) {
  $instance = "twi:" . sanitize($_GET["i"]);
}
else if(isset($_GET["s"])) {
  $instance = "tw:" . sanitize($_GET["s"]);
}
else {
  twerror();
  $instance = "<?=\$instance?>" ;
}

header("Content-type: text/plain");
?>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tw: <http://tw.rpi.edu/schema/>
PREFIX twi: <http://tw.rpi.edu/instances/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DESCRIBE ?pub ?person ?event ?super ?journal
WHERE {
  OPTIONAL {
    ?pub rdf:type tw:Publication .
    ?pub tw:hasAgentWithRole ?thisauthor .
    ?thisauthor rdf:type tw:Author .
    <?=$instance?> tw:hasRole ?thisauthor .
    ?pub tw:hasDate ?date .
    ?pub tw:hasAgentWithRole ?coauthor .
    ?person tw:hasRole ?author .
    OPTIONAL {
      ?pub tw:inEvent ?event .
      OPTIONAL {
        ?event tw:inEvent ?super
      }
    }
    OPTIONAL {
      ?pub tw:inPublication ?journal .
    }
  }
}
