# NOTE: This is hard coded to InferenceWebProject and should be generalized for other projects. -lebot 2011 Jul 16
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tw: <http://tw.rpi.edu/schema/>
PREFIX twi: <http://tw.rpi.edu/instances/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DESCRIBE ?pres ?author ?person ?event ?super ?journal
WHERE {
  [] a tw:SelectedWork;
     tw:hasSelector         twi:Deborah_L_McGuinness;
     tw:hasSelectionContext twi:InferenceWebProject;
     tw:hasSelection        ?pres .

  ?pres tw:hasProjectReference twi:InferenceWebProject .
  ?pres rdf:type tw:Presentation .
  ?pres tw:hasDate ?date .
  ?pres tw:hasAgentWithRole ?author .
  ?person tw:hasRole ?author .
  OPTIONAL {
    ?pres tw:inEvent ?event .
    OPTIONAL {
      ?event tw:inEvent ?super
    }
  }
}

